blank_issues_enabled: false
contact_links:
  - name: Ask Question
    url: https://discord.com/channels/1025686915070046248/1028785856812683346
    about: Ask questions and discuss with other community members